// <auto-generated />
using System;
using Data.Command.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Command.Migrations
{
    [DbContext(typeof(DbContexts))]
    [Migration("20260130060704_Adition Rules for DOctor and AuthUser Relations Corections One to ONe")]
    partial class AditionRulesforDOctorandAuthUserRelationsCorectionsOnetoONe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("nAuthRoleId");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea")
                        .HasColumnName("fAvatar");

                    b.Property<string>("Ci")
                        .HasColumnType("text")
                        .HasColumnName("sCi");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sFirstName");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsAdmin");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("sLastName");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("sNit");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("sPhone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sUserKey");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sUserName");

                    b.HasKey("Id");

                    b.ToTable("AuthUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthRoleId = 1,
                            Ci = "12890978",
                            Computed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Favian Alejandro",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Avila Mancilla",
                            Nit = "12890978018",
                            Phone = "67394939",
                            Status = false,
                            UserCode = 0,
                            UserKey = "jtgmad1wp",
                            UserName = "kuper"
                        },
                        new
                        {
                            Id = 2,
                            AuthRoleId = 1,
                            Ci = "User Ci",
                            Computed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Usuario",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Defecto",
                            Nit = "Client Nit",
                            Phone = "",
                            Status = false,
                            UserCode = 0,
                            UserKey = "123456",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUserConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserConfigurationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllItemsSale")
                        .HasColumnType("boolean")
                        .HasColumnName("bAllItemsSale");

                    b.Property<bool?>("AllItemsShopping")
                        .HasColumnType("boolean")
                        .HasColumnName("bAllItemsShopping");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserId");

                    b.Property<int?>("AuthUserId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<int?>("CountItemsSale")
                        .HasColumnType("integer")
                        .HasColumnName("nCountItemsSale");

                    b.Property<int?>("CountItemsShopping")
                        .HasColumnType("integer")
                        .HasColumnName("nCountItemsShopping");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("PrintNoteSale")
                        .HasColumnType("boolean")
                        .HasColumnName("bPrintNoteSale");

                    b.Property<bool?>("PrintNoteShopping")
                        .HasColumnType("boolean")
                        .HasColumnName("bPrintNoteShopping");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("AuthUserId1")
                        .IsUnique();

                    b.ToTable("AuthUserConfiguration");
                });

            modelBuilder.Entity("Domain.Entities.Classifiers.AuthRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nAuthRoleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sDescription");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.ToTable("AuthRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Computed = new DateTime(2026, 1, 30, 6, 7, 4, 112, DateTimeKind.Utc).AddTicks(5342),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Administrador",
                            Status = true,
                            UserCode = 1
                        },
                        new
                        {
                            Id = 2,
                            Computed = new DateTime(2026, 1, 30, 6, 7, 4, 112, DateTimeKind.Utc).AddTicks(5353),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doctor",
                            Status = true,
                            UserCode = 1
                        },
                        new
                        {
                            Id = 3,
                            Computed = new DateTime(2026, 1, 30, 6, 7, 4, 112, DateTimeKind.Utc).AddTicks(5354),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paciente",
                            Status = true,
                            UserCode = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.DoctorAggregate.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nDoctorId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserId");

                    b.Property<string>("Ci")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sCi");

                    b.Property<int?>("ClientZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("nClientZoneId");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sCompany");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sFirstName");

                    b.Property<bool?>("HasPhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("bHasPhoto");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("IsEmergency")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsEmergency");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sLastName");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("nLatitude");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sLink");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("nLongitude");

                    b.Property<string>("Nit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sNit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sPhone");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("sPhoto");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sReference");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<string>("Ubication")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sUbication");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Options.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nOptionsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sCode");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sDescription");

                    b.Property<bool?>("HasPicture")
                        .HasColumnType("boolean")
                        .HasColumnName("bHasPicture");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("fPicture");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sTitle");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Domain.Entities.Options.OptionsDiasnostic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nOptionsDiasnosticId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sCode");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sDescription");

                    b.Property<bool?>("HasPicture")
                        .HasColumnType("boolean")
                        .HasColumnName("bHasPicture");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<int>("OptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("nOptionsId");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("fPicture");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sTitle");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.HasIndex("OptionsId");

                    b.ToTable("OptionsDiasnostic");
                });

            modelBuilder.Entity("Domain.Entities.Options.OptionsTratament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nOptionsTratamentId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sCode");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sDescription");

                    b.Property<bool?>("HasPicture")
                        .HasColumnType("boolean")
                        .HasColumnName("bHasPicture");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<int>("OptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("nOptionsId");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("fPicture");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sTitle");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.HasIndex("OptionsId");

                    b.ToTable("OptionsTratament");
                });

            modelBuilder.Entity("Domain.Entities.PatientAggregate.ClinicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nClinicalHistoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<DateTime>("DateQuery")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dDateQuery");

                    b.Property<string>("Diagnostic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sDiagnostic");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("nDoctorId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<string>("Motive")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sMotive");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sObservations");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("nPatientId");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("nStatusId");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("tTotalCost");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.Property<bool?>("WasPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("bWasPaid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicalHistory");
                });

            modelBuilder.Entity("Domain.Entities.PatientAggregate.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nPatientId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserId");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sCi");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("nCityId");

                    b.Property<string>("CodeVerified")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sCodeVerified");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sCompany");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("integer")
                        .HasColumnName("nDepartamentId");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("nDoctorId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sFirstName");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer")
                        .HasColumnName("nGenderId");

                    b.Property<bool?>("HasPhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("bHasPhoto");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsVerified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sLastName");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("nLatitude");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sLink");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("nLongitude");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sNit");

                    b.Property<int?>("PatientZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("nPatientZoneId");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sPhone");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sPhoto");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sReference");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<string>("Ubication")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sUbication");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUserConfiguration", b =>
                {
                    b.HasOne("Domain.Entities.AuthAggregate.AuthUser", "AuthUser")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.AuthAggregate.AuthUserConfiguration", "AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AuthAggregate.AuthUser", null)
                        .WithOne("AuthUserConfiguration")
                        .HasForeignKey("Domain.Entities.AuthAggregate.AuthUserConfiguration", "AuthUserId1");

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("Domain.Entities.DoctorAggregate.Doctor", b =>
                {
                    b.HasOne("Domain.Entities.AuthAggregate.AuthUser", "AuthUser")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DoctorAggregate.Doctor", "AuthUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("Domain.Entities.Options.OptionsDiasnostic", b =>
                {
                    b.HasOne("Domain.Entities.Options.Options", null)
                        .WithMany("Diasnostics")
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Options.OptionsTratament", b =>
                {
                    b.HasOne("Domain.Entities.Options.Options", null)
                        .WithMany("Trataments")
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PatientAggregate.ClinicalHistory", b =>
                {
                    b.HasOne("Domain.Entities.PatientAggregate.Patient", null)
                        .WithMany("ClinicalHistorys")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PatientAggregate.Patient", b =>
                {
                    b.HasOne("Domain.Entities.AuthAggregate.AuthUser", "AuthUser")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.PatientAggregate.Patient", "AuthUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUser", b =>
                {
                    b.Navigation("AuthUserConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Options.Options", b =>
                {
                    b.Navigation("Diasnostics");

                    b.Navigation("Trataments");
                });

            modelBuilder.Entity("Domain.Entities.PatientAggregate.Patient", b =>
                {
                    b.Navigation("ClinicalHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
