// <auto-generated />
using System;
using Data.Command.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Command.Migrations
{
    [DbContext(typeof(DbContexts))]
    [Migration("20260130043931_Create Initial DB")]
    partial class CreateInitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("nAuthRoleId");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea")
                        .HasColumnName("fAvatar");

                    b.Property<string>("Ci")
                        .HasColumnType("text")
                        .HasColumnName("sCi");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sFirstName");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsAdmin");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("sLastName");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("sNit");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("sPhone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sUserKey");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sUserName");

                    b.HasKey("Id");

                    b.ToTable("AuthUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthRoleId = 1,
                            Ci = "12890978",
                            Computed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Favian Alejandro",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Avila Mancilla",
                            Nit = "12890978018",
                            Phone = "67394939",
                            Status = false,
                            UserCode = 0,
                            UserKey = "jtgmad1wp",
                            UserName = "kuper"
                        },
                        new
                        {
                            Id = 2,
                            AuthRoleId = 1,
                            Ci = "User Ci",
                            Computed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Usuario",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Defecto",
                            Nit = "Client Nit",
                            Phone = "",
                            Status = false,
                            UserCode = 0,
                            UserKey = "123456",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUserConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserConfigurationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllItemsSale")
                        .HasColumnType("boolean")
                        .HasColumnName("bAllItemsSale");

                    b.Property<bool?>("AllItemsShopping")
                        .HasColumnType("boolean")
                        .HasColumnName("bAllItemsShopping");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer")
                        .HasColumnName("nAuthUserId");

                    b.Property<int?>("AuthUserId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Computed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCompDate");

                    b.Property<int?>("CountItemsSale")
                        .HasColumnType("integer")
                        .HasColumnName("nCountItemsSale");

                    b.Property<int?>("CountItemsShopping")
                        .HasColumnType("integer")
                        .HasColumnName("nCountItemsShopping");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dCreate");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("bIsActive");

                    b.Property<bool?>("PrintNoteSale")
                        .HasColumnType("boolean")
                        .HasColumnName("bPrintNoteSale");

                    b.Property<bool?>("PrintNoteShopping")
                        .HasColumnType("boolean")
                        .HasColumnName("bPrintNoteShopping");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("bStatus");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("nUsercode");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("AuthUserId1")
                        .IsUnique();

                    b.ToTable("AuthUserConfiguration");
                });

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUserConfiguration", b =>
                {
                    b.HasOne("Domain.Entities.AuthAggregate.AuthUser", "AuthUser")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.AuthAggregate.AuthUserConfiguration", "AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AuthAggregate.AuthUser", null)
                        .WithOne("AuthUserConfiguration")
                        .HasForeignKey("Domain.Entities.AuthAggregate.AuthUserConfiguration", "AuthUserId1");

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("Domain.Entities.AuthAggregate.AuthUser", b =>
                {
                    b.Navigation("AuthUserConfiguration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
